apiVersion: v1
kind: Service
metadata:
  name: obench-master
  labels:
    app: obench
    tier: obench-master
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: obench
    tier: obench-master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: obench-master
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: obench
  #   tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: obench
  #     tier: frontend
  template:
    metadata:
      labels:
        app: obench
        tier: obench-master
    spec:
      containers:
      - name: obench
        image: mitake/obench
        command: ["obench", "master"]
        args: ["--nr-workers", "100"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 8080
